id: 7ef9016c-9f03-41a0-8c53-3aa95ead6da3
version: 18
vcShouldKeepItemLegacyProdMachine: false
name: Password Reset Sub-Playbook Source User Name
description: Sub-playbook that will reset and optionally expire a user's password
  using the XSOAR Sub-playbook that will reset and optionally expire a user's password
  using the XSOAR Engineer Training integration.Engineer Training integration.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 93ec2b7e-c2a9-463b-8e5a-6ae0447f20ed
    type: start
    task:
      id: 93ec2b7e-c2a9-463b-8e5a-6ae0447f20ed
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 33131ecf-cc84-44b7-8a33-cc84dd9a3c7a
    type: regular
    task:
      id: 33131ecf-cc84-44b7-8a33-cc84dd9a3c7a
      version: -1
      name: Generate New Password
      description: "This function generates a password and allows various parameters
        to customize the properties of the password depending on the use case (e.g.
        password complexity requirements).  The default behavior is to generate a
        password of  *random length* including all four character classes (upper,
        lower, digits, symbols) with at least five and at most ten characters per
        class. \n\nThe min_* values all default to 0. This means that if the command
        is executed in this way:\n!GeneratePassword max_lcase=10\nIt is possible that
        a password of length zero could be generated. It is therefore recommended
        to always include a min_* parameter that matches. \n\nThe debug parameter
        will print certain properties of the command into the WarRoom for easy diagnostics."
      scriptName: GeneratePassword
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      min_digits:
        simple: "2"
      min_lcase:
        simple: "2"
      min_symbols:
        simple: "2"
      min_ucase:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: f574dd7d-fdee-461d-8111-96086e914a44
    type: regular
    task:
      id: f574dd7d-fdee-461d-8111-96086e914a44
      version: -1
      name: Reset User Password
      description: Sets a new password for an Active Directory user.
      script: XSOAR Engineer Training|||xet-ad-set-new-password
      type: regular
      iscommand: true
      brand: XSOAR Engineer Training
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      password:
        simple: ${NEW_PASSWORD}
      username:
        simple: ${incident.sourceusername}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b63d260c-c84c-44a7-8dd5-29704bd73701
    type: regular
    task:
      id: b63d260c-c84c-44a7-8dd5-29704bd73701
      version: -1
      name: Expire Password
      description: Expires the password of an Active Directory user.
      script: XSOAR Engineer Training|||xet-ad-expire-password
      type: regular
      iscommand: true
      brand: XSOAR Engineer Training
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      username:
        simple: ${incident.sourceusername}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 4f15bd17-90d8-41af-85fa-128be89af292
    type: title
    task:
      id: 4f15bd17-90d8-41af-85fa-128be89af292
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 30e74520-17c1-4134-8ce4-9e93783872a5
    type: condition
    task:
      id: 30e74520-17c1-4134-8ce4-9e93783872a5
      version: -1
      name: Is input expire Password set to yes?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.expirePassword
            iscontext: true
          right:
            value:
              simple: "yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: souceUserName
  value:
    simple: ${incident.sourceusername}
  required: true
  description: '[Required] The samAccountName of the User to reset and expire their
    password.'
  playbookInputQuery: null
- key: expirePassword
  value:
    simple: "yes"
  required: false
  description: '["yes", "no"] Set to "yes" to expire the password for the User. Set
    to "no" to skip password expiration.'
  playbookInputQuery: null
inputSections:
- inputs:
  - souceUserName
  - expirePassword
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - NEW_PASSWORD
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: NEW_PASSWORD
  description: The new password generated for the user.
dirtyInputs: true
