id: 58588969-a87f-4d6c-8173-7c7262595797
version: 14
vcShouldKeepItemLegacyProdMachine: false
name: Password Reset Sub-Playbook Loop Example
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 44c9982f-438a-4258-84d1-ac504a3613c1
    type: start
    task:
      id: 44c9982f-438a-4258-84d1-ac504a3613c1
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: de87f7fb-543c-41b9-8895-b94ad306f1ac
    type: regular
    task:
      id: de87f7fb-543c-41b9-8895-b94ad306f1ac
      version: -1
      name: Generate New Password
      description: "This function generates a password and allows various parameters
        to customize the properties of the password depending on the use case (e.g.
        password complexity requirements).  The default behavior is to generate a
        password of  *random length* including all four character classes (upper,
        lower, digits, symbols) with at least five and at most ten characters per
        class. \n\nThe min_* values all default to 0. This means that if the command
        is executed in this way:\n!GeneratePassword max_lcase=10\nIt is possible that
        a password of length zero could be generated. It is therefore recommended
        to always include a min_* parameter that matches. \n\nThe debug parameter
        will print certain properties of the command into the WarRoom for easy diagnostics."
      scriptName: GeneratePassword
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      min_digits:
        simple: "2"
      min_lcase:
        simple: "2"
      min_symbols:
        simple: "2"
      min_ucase:
        simple: "2"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: ade38d0c-6329-457f-8d79-9da1b5e2a383
    type: regular
    task:
      id: ade38d0c-6329-457f-8d79-9da1b5e2a383
      version: -1
      name: Reset User Password
      description: Sets a new password for an Active Directory user.
      script: XSOAR Engineer Training|||xet-ad-set-new-password
      type: regular
      iscommand: true
      brand: XSOAR Engineer Training
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      password:
        simple: ${NEW_PASSWORD}
      username:
        simple: ${inputs.Users}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: b3480236-5a1b-4c57-8d3e-fce9a6165460
    type: regular
    task:
      id: b3480236-5a1b-4c57-8d3e-fce9a6165460
      version: -1
      name: Expire Password
      description: Expires the password of an Active Directory user.
      script: XSOAR Engineer Training|||xet-ad-expire-password
      type: regular
      iscommand: true
      brand: XSOAR Engineer Training
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      username:
        simple: ${inputs.Users}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 971eb017-64a9-479a-84c0-9b7e888f0fd8
    type: title
    task:
      id: 971eb017-64a9-479a-84c0-9b7e888f0fd8
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: dcc10683-5e5b-4cdf-8b71-0c5e9e616b76
    type: condition
    task:
      id: dcc10683-5e5b-4cdf-8b71-0c5e9e616b76
      version: -1
      name: Is input expire Password set to yes?
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.expirePassword
            iscontext: true
          right:
            value:
              simple: "yes"
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: d2327c62-ae56-4ece-8309-3e4e0101bc00
    type: regular
    task:
      id: d2327c62-ae56-4ece-8309-3e4e0101bc00
      version: -1
      name: Delete Context
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      key:
        simple: NEW_PASSWORD
      subplaybook:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 4c0a4b27-1039-4ae0-8c59-fb8e4664fde7
    type: regular
    task:
      id: 4c0a4b27-1039-4ae0-8c59-fb8e4664fde7
      version: -1
      name: Set User and Password to Context
      description: Set multiple keys/values to the context.
      scriptName: SetMultipleValues
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      keys:
        simple: User,Password
      parent:
        simple: Passwords
      values:
        simple: ${inputs.Users},${NEW_PASSWORD}
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1260,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: Users
  value:
    simple: ${Users}
  required: false
  description: ""
  playbookInputQuery: null
- key: expirePassword
  value:
    simple: "yes"
  required: false
  description: ""
  playbookInputQuery: null
inputSections:
- inputs:
  - Users
  - expirePassword
  name: General (Inputs group)
  description: Generic group for inputs
outputSections:
- outputs:
  - NEW_PASSWORD
  - Passwords
  name: General (Outputs group)
  description: Generic group for outputs
outputs:
- contextPath: NEW_PASSWORD
  type: unknown
- contextPath: Passwords
  type: unknown
quiet: true
dirtyInputs: true
